micronaut:
 application:
  name: weighter
 security:
  authentication: session
  endpoints:
   login:
    path: /login/auth
  redirect:
   login-success: /main
   login-failure: /login/authFailed
   unauthorized:
     url: /login/auth
  intercept-url-map:
   - pattern: /static/**
     http-method: GET
     access:
      - isAnonymous()
   - pattern: /main
     http-method: POST
     access:
      - isAnonymous()
 router:
  static-resources:
   default:
    enabled: true
    mapping: /static/**
    paths: classpath:static